baseURL = "http://divingfor.fun/"
languageCode = "en-us"
title = "Diving for fun dive adventures blog by Martin Splitt"
theme = "zzo"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

googleAnalytics = "UA-33444478-3"

[markup.goldmark.renderer] 
  unsafe= true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[outputs]
  page = ["HTML", "SearchIndex"]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true