[[main]]
identifier = "galleries"
name = "Galleries"
url = "gallery"
weight = 1

# [[main]]
# identifier = "dives"
# name = "Dive reports"
# url = "dives"
# weight = 2

[[main]]
identifier = "divesites"
name = "Dive sites"
url = "divesites"
weight = 3

[[main]]
identifier = "trips"
name = "Dive trips"
url = "trips"
weight = 4

[[main]]
identifier = "about"
name = "About"
url = "about"
weight = 5
