baseURL = "https://divingfor.fun/"
languageCode = "en-us"
title = "Diving for fun dive adventures blog"
theme = "zzo"

[params]
    favicon = "favicon.ico"
    description = "The diving adventures of Martin Splitt"
    themeOptions = ["light"]
    summaryShape = "classic"
    archiveGroupByDate = "2006-02"
[Author]
    name = "Martin Splitt"
