baseURL = "https://divingfor.fun/"
languageCode = "en-us"
title = "Diving for fun dive adventures blog"
theme = "ticky_tacky_dark"

[params]
    favicon = "favicon.ico"
    description = "The diving adventures of Martin Splitt"
    images = ["img/header01.jpg", "img/header02.jpg"]
    #msvalidate = ""
    #googlesiteverification = ""

[Author]
    name = "Martin Splitt"
