name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      run: |
        git clone https://github.com/gohugoio/hugo.git
        cd hugo
        go install
        go build
        chmod +x hugo
        cd ..
    - name: Build site
      run: |
        hugo/hugo -D --minify
    - name: Deploy to Surge
      run: |
        export SURGE_LOGIN=mr.avgp@gmail.com
        export SURGE_TOKEN=14702e250c70d050c8d27d0239e1f61a
        npm i surge
        node_modules/.bin/surge public divingfor.fun
