name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      run: |
        git clone https://github.com/gohugoio/hugo.git
        cd hugo
        go install
        go build
        chmod +x hugo
        cd ..
    - name: Build site
      run: |
        hugo/hugo -D --minify
    - name: Deploy to Surge
      run: |
        export SURGE_LOGIN={{Secrets.SurgeLogin}}
        export SURGE_TOKEN={{Secrets.SurgeToken}}
        npm i surge
        cd public
        ../node_modules/.bin/surge . divingfor.fun
